### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by wneves** [fieldOfView/Cura-MeasureTool#5] opened 2021-02-06 14:25 UTC
Hi. Please make a tutorial to understand how to install the plug-in.

**Comment by fieldOfView** [comment] 2021-02-06 15:19
Duplicate of https://github.com/fieldOfView/Cura-MeasureTool/issues/3

In short: this plugin is a work in progress. Don't use it.

**Closed by fieldOfView** 2021-02-06 15:19 UTC

**Comment by fieldOfView** [comment] 2021-04-07 22:12
A test version can now be found here:
https://community.ultimaker.com/topic/36573-measure-tool-plugin/?tab=comments#comment-286716
