### ISSUE TITLE
Wrapped C/C++ object of type QQuickItem has been deleted

### ISSUE THREAD

**Issue by Ghostkeeper** [fieldOfView/Cura-MeasureTool#8] opened 2021-06-08 12:11 UTC
We're seeing an error come up relatively frequently in Cura's error tracing, from this plug-in:

https://sentry.io/share/issue/50c589e007944051a93c3cdac66e2e47/

The error has currently been seen 344 times, from 216 (estimated) users. It was first seen a month ago, but is also seen in Cura 4.8 and 4.6 (although most crashes are in 4.9).

I think you might need to change the ownership of this object to Cpp (Python) rather than Qt? Or maybe find a way to implement this in a different way.

You can't see the log snippet that we store there in the public share link, but here is a snippet that hints that this issue might occur when switching to the Monitor page:
![image](https://user-images.githubusercontent.com/2448634/121182206-23a0f280-c863-11eb-8857-1b4ccee93310.png)

**Comment by fieldOfView** [comment] 2021-06-08 15:05
I can't reproduce this issue. Can you at least share the whole traceback?

Changing the ownership of the object is not possible since it is an object that is created by Uranium elsewhere. I have to jump through some hoops in questionable ways to keep the tool enabled when no model is selected. I can catch and handle the runtimeerror in question, but I can't tell if this would crop up elsewhere without a way to reproduce.

**Comment by fieldOfView** [comment] 2021-06-08 15:22
Can you see what other plugins these users have installed?

**Comment by Ghostkeeper** [comment] 2021-06-09 09:56
> Can you at least share the whole traceback?

The traceback you see there is the whole traceback as far as I have it. It starts from `CuraApplication.event` because it's called from the Qt event loop. This Sentry software is unable to show the source code near some of the code if the source code changed since the event happened, but it is able to show that it started in the MeasureTool from `_onSelectionChanged`.

Indeed I can! And looking through the instances, it appears like most of these seem to be from users who install more or less all plug-ins from the Marketplace. This one was the smallest list that I could find clicking through them for a few minutes:
![image](https://user-images.githubusercontent.com/2448634/121333548-31b14a80-c919-11eb-8a28-bfde661d4f09.png)

**Comment by fieldOfView** [comment] 2021-06-09 15:40
Thanks. Out of the listed plugins, I can see that the (Teton) SmartSlicePlugin manipulates the toolbar (showing and hiding tools), so that's a likely culprit of conflicts.

**Comment by fieldOfView** [comment] 2021-06-11 09:41
Confirmed the crash in combination with Teton Smart Slice plugin. Fixed in the current master. I'll leave this issue open until a new release is published on the Marketplace.

**Closed** 2021-06-21 08:50 UTC
Labels: bug, fixed
